baseURL = 'https://www.temperancee.xyz'
languageCode = 'en-gb'
title = "temperancee's website"
theme = 'anubis2'
enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 5

[params.author]
name = "temperancee"

[params]
# toc = false

[params.anubis2]
    enableMathGlobally = true
    enableCopyCodeButton = true
    enableColorThemeSwitcher = true
    enableReadMoreButton = true

    social = [
        { id = "github", url = "https://github.com/temperancee" },
        { id = "linkedin", url = "https://www.linkedin.com/in/myles-foy-856875279/" },
        { id = "email", url = "mfoy1655@yahoo.com" }
        # { id = "youtube", url = "https://youtube.com/@temperanceeeee" }
    ]
    colorTheme = "dark"
    
    customCSS = [
        "css/homepage.css"
    ]

[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "blog"
identifier = "blog"
url = "/blog/"
weight = 4

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = false # Enable unsafe mode to have a better experience
    [markup.goldmark.parser]
        autoHeadingID = false

[markup.highlight]
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
